- scripts/postinstall.js
Use native methods in post-install
Signed-off-by: Miki <miki@amazon.com>
> Avoid using dev-deps in post-install script

- .github/workflows/backport.yml
- .github/workflows/delete_backport_branch.yml
> Backport workflow

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- DEVELOPER_GUIDE.md
- LICENSE.txt
- MAINTAINERS.md
> Add GitHub templates

- src/themes/oui-cascadia/overrides/_button.scss
- src/themes/oui-cascadia/overrides/_mark.scss
- yarn.lock
Fix lint errors
* Lockdown cheerio to rc.8
* SCSS spacing
* Incorrect alias classname
Signed-off-by: Miki <miki@amazon.com>
> Fix lint errors

- CHANGELOG.md
Signed-off-by: kgcreative <kvngar@amazon.com>
Add OUI & EUI Headers to changelog
- There is one failed test in date_format.text.ts, which none of the files here modify
> Update changelog to disambiguate OUI from EUI

- src-docs/src/assets/version-selector.js
- src-docs/src/components/guide_page/guide_page_header.tsx
Allow user to choose OUI Doc Site from different versions
[Issue-73](https://github.com/opensearch-project/oui/issues/73)
> [Docsite] Implement dropdown to choose different OUI Docsite Versions

- src-docs/src/components/guide_page/guide_page_header.tsx
Trim package json version. for e.g 1.0.0 to 1.0
> fix drodown bug

- src-docs/src/components/guide_page/guide_page_header.tsx
Signed-off-by: Kartik <xdeskart@amazon.com>
Update interface for version-selector
> fix interface

- MAINTAINERS.md
- src-docs/src/components/guide_page/guide_page_header.tsx
updated the maintainers md with new team members 
updated the maintainers md ith new team members for consistency
> updated the maintainers md

- src/components/form/field_password/__snapshots__/field_password.test.tsx.snap
- src/components/form/field_password/field_password.tsx
Disable spellcheck on password field
> Disable spellcheck on password field

- .whitesource
- whitesource.config
Brings parity between OUI's and OSD's WhiteSource configuration. It seems that previously, WhiteSource wasn't configured correctly and didn't generate the #166 issue. This should hopefully solve that.
> Add WhiteSource config file

- src-docs/src/views/bottom_bar/bottom_bar_position.js
Changed the text in the section Positions from "Scroll to see!" to "Scroll for demo"
#172 
> Updated text in Section Positions

- src-docs/src/views/resizable_container/resizable_container_basic.js
- src-docs/src/views/resizable_container/resizable_panel_collapsible.js
- src-docs/src/views/resizable_container/resizable_panel_collapsible_options.js
- src-docs/src/views/resizable_container/resizable_panel_collapsible_responsive.js
Updated the required sections of the resizable container.
https://user-images.githubusercontent.com/62020972/217378328-7edbf008-5108-4f00-9e51-b384edb300c4.mov
#187 
> Updated the Reziable container

- src-docs/src/views/title/title_example.js
Updated in the title section from Kibana to Opensearch Dashboards.
#273 
> [OUI Docs] updated the title section

- src-docs/src/views/form_layouts/described_form_group.js
- src-docs/src/views/form_layouts/form_rows.js
Updated the links to opensearch.org in the section Form Layout.
https://user-images.githubusercontent.com/62020972/218175984-9344a119-3aaf-4b5e-b238-dccaae8e1465.mov
https://user-images.githubusercontent.com/62020972/218175996-43d91ee3-f5e2-4bba-ab9e-b6348684c20a.mov
#279 
> [OUI Docs] Updated the links in the section Form Layout

- src-docs/src/views/side_nav/side_nav_complex.js
- src-docs/src/views/side_nav/side_nav_force_open.js
Updated the content in the section side nav.
#215 
> Updated Side nav

- src-docs/src/views/tool_tip/icon_tip.js
- src-docs/src/views/tool_tip/tool_tip.js
- src-docs/src/views/tool_tip/tool_tip_example.js
Updated the content in the section ToolTip.
#275 
> [OUI Docs] Updated the content for the ToolTip

- src-docs/src/views/tables/actions/actions.js
- src-docs/src/views/tables/footer/footer.js
- src-docs/src/views/tables/in_memory/in_memory.js
- src-docs/src/views/tables/in_memory/in_memory_controlled_pagination.js
- src-docs/src/views/tables/in_memory/in_memory_search.js
- src-docs/src/views/tables/in_memory/in_memory_search_callback.js
- src-docs/src/views/tables/in_memory/in_memory_search_external.js
- src-docs/src/views/tables/in_memory/in_memory_selection.js
- src-docs/src/views/tables/mobile/mobile.js
- src-docs/src/views/tables/paginated/paginated.js
- src-docs/src/views/tables/selection/selection.js
- src-docs/src/views/tables/sorting/sorting.js
Clean the reference in src-docs/src/views/tables
https://github.com/opensearch-project/oui/issues/234
> Clean table doc ref

- src/components/icon/assets/logo_opensearch.js
- src/components/icon/assets/logo_opensearch.svg
Create an OpenSearch logo
https://github.com/opensearch-project/oui/issues/369
> Add OpenSearch logo

- src-docs/src/components/guide_page/guide_page.js
- src-docs/src/views/tour/managed.js
- src-docs/src/views/tour/managed_hook.js
- src-docs/src/views/tour/tour.js
- yarn.lock
Delete all ES reference in tour page, and change the beta badge to experimental.
#276 
> Delete ES reference in tour page

- src-docs/src/views/aspect_ratio/aspect_ratio.js
Updated the Podcast in the section Aspect Ratio.
#375 
> [OUI Docs] Updated the Podcast in the section Aspect Ratio

- src-docs/src/views/aspect_ratio/aspect_ratio.js
- src-docs/src/views/aspect_ratio/playground.js
Updated the YouTube embed in the section Aspect ratio.
https://user-images.githubusercontent.com/62020972/220452271-e03b44fd-66bf-486d-9a66-2c6b88a81958.mov
#233 
> [OUI Docs] Updated the youtube embed in the section Aspect ratio

- src-docs/src/views/utility_classes/utility_classes_overflow.js
- src-docs/src/views/utility_classes/utility_classes_text.js
- src-docs/src/views/utility_classes/utility_classes_vert_align.js
Updated the content and Icons in the section CssUtilityClasses.
#344 
> [OUI Docs] Updated the content and Icons in the section CssUtilityClasses

- src-docs/src/views/avatar/avatar_initials.js
- src-docs/src/views/avatar/avatar_type.js
Signed-off-by: Matt Provost <provomat@amazon.com>
Update docs for avatar to match the changes prescribed in the issue
#240
> Update avatar docs

- ADMINS.md
- DEVELOPER_GUIDE.md
- README.md
- RESPONSIBILITIES.md
- SECURITY.md
baselined against https://github.com/opensearch-project/.github
- Add ADMINS.md
- Update DEVELOPER_GUIDE.md - move running instructions from README.md, remove doc site links
- Add RESPONSIBILITIES.md
- Add SECURITY.md
#103 
> [Docs] Update README to baseline to project standards

- src-docs/src/views/selectable/selectable_example.js
- src-docs/src/views/selectable/selectable_messages.tsx
Updated the content in the section Messages and loading.
#329 
> [OUI Docs] Updated the content in the section Messages and loading

- src-docs/src/views/markdown_editor/markdown_format_sink.js
Updated the links in the section Markdown Format.
https://user-images.githubusercontent.com/62020972/220237919-b9a4beec-0175-429a-8e76-514db2107c03.mov
#335 
> [OUI Docs] Updated the links in the section Markdown Format

- src-docs/src/views/toast/danger.js
- src-docs/src/views/toast/guidelines.js
Updated the content in the section toast.
#274 
> [OUI Docs] Updated the content in the section Toast

- src-docs/src/views/datagrid/datagrid_example.js
- src-docs/src/views/datagrid/schema.js
Updated the content for the Section: Disabling expansion popovers and Table column "custom"
#228 
> [OUI DOCS] Updated the content in the section Datagrid and schema

- .github/workflows/backport.yml
Update the backport workflow to match OpenSearch Dashboards
> Update backport workflow

- package.json
Bump version number to `1.0.1-rc.1` in preparation for release
> [1.0] Bump version number to `1.0.1-rc.1`

- src-docs/src/index.js
- src-docs/src/theme_pink_elephant.scss
- src/theme_pink_elephant.scss
- src/themes/oui/oui_colors_pink_elephant.scss
- src/themes/themes.ts
Implements the Pink Elephant and more broadly any theme in the future.
Fixes #556 
> Implement Pink Elephant

- src-docs/src/index.html
- src-docs/src/views/card/card_image.js
- wiki/creating-components-manually.md
- wiki/creating-icons.md
- wiki/documentation-guidelines.md
- wiki/releasing-versions.md
Update Elastic links to OpenSearch ones
https://github.com/opensearch-project/oui/issues/557
> [CCI] Update Elastic links to OpenSearch ones (#557)

- package.json
Update version to prepare for Pink Elephant release
> Update Pink Elephant version

- package.json
Bump version to `1.1.0-rc.4` for new RC release
> [1.1] Bump version to 1.1.0-rc.4

- package.json
> [1.1] Bump version to 1.1.0

- src/components/date_picker/super_date_picker/super_date_picker.tsx
Revert the super date picker changes for 1.1.0. This helps support Dashboards 2.7 release, as some important tests are failing because of this and we don't have time to figure out how to fix them.
> Revert "Rectify super date picker functionality (#627) (#682)"

- .github/workflows/release-drafter.yml
Fix the issue caused in https://github.com/opensearch-project/oui/actions/runs/5093751017/jobs/9156740879
> Fix release drafter workflow

- MAINTAINERS.md
Update affiliation of Andrey and Sergey to Contributor. We agreed that this would be the best thing to put, as we didn't want to leave it blank.
> Update affiliation of Andrey and Sergey

- FAQ.md
[Describe what this change achieves]
Can I use OUI? [FAQ.md](https://github.com/opensearch-project/oui/issues/url) refers to [https://github.com/opensearch-project/oui/blob/main/LICENSE](https://github.com/opensearch-project/oui/issues/url) I fixed the to the valid link
fixes #738
> fixed invalid link in FAQ.md

- .github/ISSUE_TEMPLATE/bug_template.md
Removed unnecessary parts (e.g. OpenSearch version), updated examples and simplified the template for better newcomer experience.
Solves https://github.com/opensearch-project/oui/issues/182
> Updated bug issue template

- package.json
- src-docs/src/views/datagrid/additional_controls.js
- src-docs/src/views/datagrid/column_actions.js
- src-docs/src/views/datagrid/column_cell_actions.js
- src-docs/src/views/datagrid/column_widths.js
- src-docs/src/views/datagrid/container.js
- src-docs/src/views/datagrid/control_columns.js
- src-docs/src/views/datagrid/datagrid.js
- src-docs/src/views/datagrid/focus.js
- src-docs/src/views/datagrid/footer_row.js
- src-docs/src/views/datagrid/in_memory.js
- src-docs/src/views/datagrid/in_memory_enhancements.js
- src-docs/src/views/datagrid/in_memory_pagination.js
- src-docs/src/views/datagrid/in_memory_sorting.js
- src-docs/src/views/datagrid/schema.js
- src-docs/src/views/datagrid/styling.js
- src-docs/src/views/datagrid/virtualization.js
- src-docs/src/views/datagrid/virtualization_constrained.js
- yarn.lock
Bump @faker-js/faker to v8. 
All changes that need to be applied during the version upgrade are shown in the console, below is a screenshot showing that all the warnings have been fixed and consequently the version upgrade was successful
https://github.com/opensearch-project/oui/issues/594
> [CCI] Bump @faker-js/faker to v8

- .github/pull_request_template.md
Change the PR template to include "Fixes" in the `Issues Resolved` section, to make it clearer to contributors on the proper format for the section. This will help maintainers by automatically closing related issues so maintainers don't have to do it manually
> Change PR template to say fixes issues

- package.json
Bump version to `1.3.0-alpha.1`. Using alpha here because more things will potentially be going into 1.3.0, so it's not yet at the point of being a release candidate.
> Bump version to 1.3.0-alpha.1

- package.json
> [1.1] Chore/bump version 1.1.2

- CHANGELOG.md
- scripts/compile-scss.js
- scripts/postinstall.js
> [New Theme] Rename aliased CSS assets

- package.json
> Bump version to 1.3.0-alpha.2

- .github/workflows/backport.yml
- CHANGELOG.md
Upgrade the backport workflow
- Copy over the labels from the original PR
- Label the backport PR with autocut
- Label a PR that fails to backport
> Upgrade the backport workflow

- package.json
Bump version to 1.3.0-beta.1 to cut a new beta release
> Bump version to 1.3.0-beta.1

- package.json
Bump version to `1.3.0-rc.1` to cut a new release
Preparation for #958 
> Bump version to `1.3.0-rc.1`

- CHANGELOG.md
- src-docs/src/views/facet/facet.js
Update "avatar as icon" example as described in #909 
Closes #909
> Replace Avatar in favor of Icon in OuiFacetButtons example

- package.json
Bump version to `1.3.0` to cut a new prod release
fixes #958 
> Bump version to `1.3.0`

- CHANGELOG.md
Update changelog for 1.3 release.
> [1.x] Update changelog for 1.3

- CHANGELOG.md
Update changelog for 1.3 release.
> [1.3] Update changelog for 1.3

- CHANGELOG.md
Update changelog with 1.1.2 and 1.2.0 info. Got changes by checking diffs on Github.
> Update changelog with 1.1.2 and 1.2.0

- CHANGELOG.md
Update changelog with 1.1 and 1.2 info. Got changes by checking diffs on Github.
> [1.x] Update changelog with 1.1 and 1.2

- DEVELOPER_GUIDE.md
Made minor changes in the developer guide so new contributors will not get confused while setting up a repo.
It is solving #1057 
> Changes made in Developer Guide

- package.json
Bump to version `2.0.0` on `main` to better reflect the version on this branch.
> Bump to version 2.0.0

- package.json
Bump version to `1.4.0-alpha.1` to prepare for release
> Bump version to 1.4.0-alpha.1

- package.json
> Bump version to 1.4.0-alpha.2

- package.json
> [1.x] Bump 1.4.0

- .github/CODEOWNERS
- CHANGELOG.md
- MAINTAINERS.md
> Move Sean to Emeritus

- CHANGELOG.md
> Sync CHANGELOG prior to 1.4 release

- package.json
> Bump version on 1.5 

- i18ntokens.json
- package.json
> Update `i18ntokens` and bump version for 1.5.0-rc.2

- CHANGELOG.md
- package.json
> Bump version to 1.5

- CHANGELOG.md
- src/components/datagrid/_data_grid_data_row.scss
Fix a bad merge from a cherry-pick
> Fix datagrid lines

- CHANGELOG.md
- package.json
Hold merging for the backport of #1250
> Bump version to 1.5.1

- .github/CODEOWNERS
- CHANGELOG.md
- MAINTAINERS.md
> Move Kroosh and Matt to Emeritus

- CHANGELOG.md
- package.json
> Bump package version to 1.6.0

- CHANGELOG.md
- DEVELOPER_GUIDE.md
- wiki/validating-with-opensearch-dashboards.md
Just adds docs to locally validate OUI changes in OpenSearch-Dashboards
> Add docs for validating OUI changes in OpenSearch-Dashboards

- CHANGELOG.md
- i18ntokens.json
- package.json
Updating changelog and version
Also, synced i18n tokens
> Updating changelog and version

- CHANGELOG.md
> Update 1.7 changelog

- .github/CODEOWNERS
- CHANGELOG.md
- MAINTAINERS.md
By sufficient vote of maintainers, adding Viraj as one.
> Add Viraj as a maintainer

- CHANGELOG.md
- package.json
> Bump version post 1.7 release

- CHANGELOG.md
- src-docs/src/views/form_controls/prepend_append.js
- src/components/form/form_control_layout/_form_control_layout.scss
Before Next
After Next
After v7
Before Next
After Next
After v7
> Fix the appearance of form controls in grouped layouts

- CHANGELOG.md
> Sync 1.x changelog

- CHANGELOG.md
> Update changelog for 1.8 release

- package.json
> Bump 1.8.1

- CHANGELOG.md
- src/components/date_picker/super_date_picker/index.ts
- src/components/index.js
> Fix export of OuiCompressedSuperDatePicker

- i18ntokens.json
- package.json
- yarn.lock
Prepare for patch release 1.8.2
Update
* i18ntokens
* caniuse-lite
* changelog
> Prepare for patch release 1.8.2

- CHANGELOG.md
> Sync changelog for 1.9.0 release

- CHANGELOG.md
- i18ntokens.json
- package.json
- yarn.lock
> Prepare for 1.9.0 release

- CHANGELOG.md
- src-docs/src/views/search_bar/props_info.js
- src/components/search_bar/__snapshots__/search_filters.test.tsx.snap
- src/components/search_bar/filters/field_value_selection_filter.tsx
- src/components/search_bar/filters/field_value_toggle_filter.tsx
- src/components/search_bar/filters/field_value_toggle_group_filter.tsx
- src/components/search_bar/filters/is_filter.tsx
- src/components/search_bar/search_bar.tsx
- src/components/search_bar/search_filters.tsx
Introduce compressed OuiSearchBar
> Introduce compressed OuiSearchBar

- CHANGELOG.md
- i18ntokens.json
- package.json
- yarn.lock
> Prepare for 1.10.0 release

- CHANGELOG.md
> Update changelog for 1.10

- CHANGELOG.md
Update changelog for 1.11 release
> Update changelog for 1.11 release

- CHANGELOG.md
Fix changelog for 1.12 release
N/A
> Fix changelog for 1.12 release

- CHANGELOG.md
- src-docs/src/views/date_picker/date_picker.js
- src-docs/src/views/date_picker/date_picker_example.js
- src-docs/src/views/date_picker/playground.js
- src-docs/src/views/date_picker/range.js
- src-docs/src/views/date_picker/states.js
- src/components/date_picker/__snapshots__/date_picker.test.tsx.snap
- src/components/date_picker/_date_picker_range.scss
- src/components/date_picker/date_picker.tsx
- src/components/date_picker/date_picker_range.tsx
* Fix compressed styling of OuiDatePickerRange
* Add compressed to OuiDatePicker
* Add playground for OuiDatePicker
> Add compressed styling to OuiDatePicker and OuiDatePickerRange

- src/themes/v9/global_styling/variables/_buttons.scss
- src/themes/v9/global_styling/variables/_colors.scss
- src/themes/v9/v9_colors_dark.scss
Updates to v9 colors per design
N/A
> fix: updates to v9 theme colors

- CHANGELOG.md
- package.json
- yarn.lock
Bump changelog and version for 1.13 release
Also:
* Update `browserslist` db
> Bump changelog and version for 1.13 release

- CHANGELOG.md
Updating changelog for 1.13 release
N/A
> 1.13 update changelog

- CHANGELOG.md
Update changelog for 1.14 release
N/A
> 1.14 udpate changelog

- CHANGELOG.md
- package.json
Bump changelog and package.json for 1.15 release
n/a
> Bump changelog and package.json for 1.15 release

- CHANGELOG.md
Update changelog for 1.15 release
N/A
> Update changelog for 1.15 release

- CHANGELOG.md
- package.json
Update changelog and package.json for 1.16 release
N/A
> Update changelog and package.json for 1.16 release

- CHANGELOG.md
Update changelog for 1.16 release
N/A
> Update changelog for 1.16 release

- CHANGELOG.md
- src/themes/v9/global_styling/variables/_buttons.scss
- src/themes/v9/global_styling/variables/_colors.scss
- src/themes/v9/global_styling/variables/_form.scss
- src/themes/v9/global_styling/variables/_shadows.scss
- src/themes/v9/global_styling/variables/_side_nav.scss
- src/themes/v9/global_styling/variables/_tool_tip.scss
- src/themes/v9/v9_colors_dark.scss
Update v9 theme colors for light and dark mode
N/A
> Update v9 theme colors for light and dark mode

- CHANGELOG.md
- package.json
Update version and changelog for 1.17 release
N/A
> Update version and changelog for 1.17 release

- CHANGELOG.md
Update changelog for 1.17 release
N/A
> Update changelog for 1.17 release

- CHANGELOG.md
- package.json
Update changelog and package.json for 1.18 release
N/A
> Update changelog and package.json for 1.18 release

- CHANGELOG.md
Update changelog for 1.18 release
N/A
> Update changelog for 1.18 release

- CHANGELOG.md
Update changelog for 1.19 release
N/A
> Update changelog for 1.19 release

- .github/CODEOWNERS
- CHANGELOG.md
- MAINTAINERS.md
Add Yulong and Daniel as maintainers
N/A
> Add Yulong and Daniel as maintainers

- CHANGELOG.md
- package.json
- yarn.lock
> resolves CVE-2024-45296. Issue 1405

- CHANGELOG.md
- package.json
- yarn.lock
Fix cve issue for transitive dependency  using : @babel/runtime-corejs2 - 7.26.10
https://github.com/opensearch-project/oui/issues/1519
https://github.com/opensearch-project/oui/issues/1518
- feat: Fix cve issue for transitive dependency @babel/runtime-corejs2
> @babel/runtime upgrade

- CHANGELOG.md
- src-docs/src/views/page_header/page_header.js
Replace logoKibana to os in page title
> Add OpenSearch logo to page title

- CHANGELOG.md
Fix changelog formatting + add automated updates
Changelog had weird formatting + two automated PRs weren't included
N/A
> Fix changelog formatting + add automated PRs

- CHANGELOG.md
Just updates changelog for #1560 and #1564 
> Update changelog for automated security fixes

- CHANGELOG.md
- package.json
Preparing for 1.20 release
N/A
> Update changelog and package.json for 1.20 release

- CHANGELOG.md
Updates changelog ahead of 1.20 release
> Fix changelog for 1.20 release

- CHANGELOG.md
Add changelog entry for #1604
N/A
> Add changelog entry for #1604

- CHANGELOG.md
Updates changelog ahead of 1.21 release
> Fix changelog for 1.21 release
