opensearch-project/oui

package.json
yarn.lock

Removes forced resolution of `bin-version-check` to a higher and incompatible version to avoid yo-doctor errors during build.

Fix yo doctor errors during build

---

package.json
yarn.lock

`codesandbox` no longer consumes `pacote` and its inclusion as dep is in error.
Signed-off-by: Miki <miki@amazon.com>

Bump `pacote` as a transitive dependency of `codesandbox`

---

package.json
yarn.lock

Fix test errors
* Lockdown cheerio to rc.5
Signed-off-by: Miki <miki@amazon.com>
Fixes #41 

Fix test errors

---

package.json
yarn.lock

Signed-off-by: kaddy645 <xdeskart@amazon.com>
**GSD-2022-25758** : All versions of the package scss-tokenizer prior to 0.4.3 are vulnerable to Regular Expression Denial of Service
**GSD-2022-33987** : The got package before 12.1.0 (also fixed in 11.8.5) for Node.js allows a redirect to a UNIX socket.
**GSD-2020-7789** : node-notifier before 8.0.1 allows attacker to run arbitrary commands on Linux machines due to the options parameters not being sanitised when being passed an array.
**GSD-2021-23382** : The package postcss versions before 7.0.36 or between 8.0.0 and 8.2.13 are vulnerable to Regular Expression Denial of Service (ReDoS) via getAnnotationURL() and loadAnnotation() in lib/previous-map.js.
**Eslint** : A vulnerability was descovered in eslint before 4.18.2. One of the regexes …

Bump packages - CVE

---

package.json
yarn.lock

Signed-off-by: kaddy645 <xdeskart@amazon.com>
As a part of package Update issue, update React to match with OSD version
[Issue](https://github.com/opensearch-project/oui/issues/56)

Bump React 16.12.0 to 16.14.0

---

package.json
yarn.lock

Signed-off-by: Bandini Bhopi <bandinib@amazon.com>
This PR resolves following issue:
GSD-2020-15366 : [Improper Input Validation,Prototype Pollution in Ajv](https://advisories.aws.barahmand.com/advisory/CVE-2020-15366)

Bump har-validator

---

.eslintrc.js
scripts/compile-icons.js

Signed-off-by: Bandini Bhopi <bandinib@amazon.com>
This PR updates the ```scripts/compile-icons``` script to include license header in the auto-generated compiled icon file. Scope of this fix is only limited to compiling existing icons. 
#37  

Fix compile icon script to include license header

---

src-docs/src/assets/version-selector.js

Fix the height of the carat for the version selector
#105 

Fix carat height

---

.github/workflows/release-drafter.yml
CHANGELOG.md
RELEASING.md
jenkins/release.JenkinsFile
package.json

This change adds release workflows to publish OUI on https://www.npmjs.com/
Please see https://github.com/opensearch-project/opensearch-build/issues/1234 for design details of end to end workflow.
TL;DR:
When a tag is pushed to this repository, it will generate a draft release. The draft release will trigger the jenkins job (see Files Changed for attached jenkins file) that publishes the client to npmjs. Once the release is successful, the drafted release is published on GitHub.
https://github.com/opensearch-project/opensearch-build/issues/2900
For more information on following Developer Certificate of Origin and signing off your commits, please check …

Add release workflows

---

package.json
yarn.lock

Update minimatch to latest patch versions

Update minimatch to 3.0.8 and 3.1.2

---

src-docs/src/views/badge/beta_badge.js
src/components/badge/beta_badge/__snapshots__/beta_badge.test.tsx.snap
src/components/badge/beta_badge/_beta_badge.scss
src/components/badge/beta_badge/beta_badge.tsx

Removes the `accent` color option for the beta badge, as per #93 

Remove beta badge accent color

---

src-docs/src/views/badge/beta_badge.js

Change documentation for beta badge text from "beta" to "experimental" as per https://github.com/opensearch-project/oui/issues/93

Change badge text to Experimental

---

package.json
yarn.lock

Patch bump qs from 6.5.3 to 6.11.0

Bump qs from 6.5.3 to 6.11.0

---

yarn.lock

Update json5 from 1.0.1 and 2.1.3 to 1.0.2 and 2.2.2 respectively, to fix security vulnerabilities in those packages.
#166 

Update json5 to 1.0.2 and 2.2.2

---

.github/workflows/build_and_test.yml

Adds a workflow to lint and test on pushes to branches and on PR's.
#157 

Add test and lint workflow

---

package.json
yarn.lock

Signed-off-by: Matt Provost <provomat@amazon.com>
Update ramda from 0.25.0 to 0.27.1

Update ramda from 0.25.0 to 0.27.1

---

src-docs/src/components/with_theme/theme_context.tsx

Signed-off-by: Matt Provost <provomat@amazon.com>
New users to the docs site are presented with an empty page because the default theme is not set correctly. It is trying to reference a theme that was removed, thus resulting in an error and nothing gets displayed.

Fix docs site default theme

---

src-docs/src/views/flex/flex_align_center.js
src-docs/src/views/flex/flex_grow_zero.tsx
src-docs/src/views/flex/flex_item.tsx
src-docs/src/views/flex/flex_justify.js
src-docs/src/views/flex/flex_justify_between.js
src-docs/src/views/flex/flex_justify_evenly.js

Updated the strings in the Flex section.
#173 

Updated text in Section Positions

---

src-docs/src/views/tabs/tabs.js

Removed the Outdated references of `elastic` and updated that with `opensearch`in the Tabs section
#217 

Removed Outdated References of elastic and updated with Opensearch.org

---

src-docs/src/views/steps/status.js
src-docs/src/views/steps/steps_complex.js

Removed the outdated reference of Elasticsearch and replaced it with Opensearch and changed the text in the step status.
#216 

Removed outdated reference and updated text in OUI doc steps

---

src-docs/src/views/tree_view/compressed.js

Removed smokeMoster from the optional styling section.
#214 

Removed smokeMoster from Optional styling

---

src-docs/src/views/modal/confirm_modal_loading.js

Removed the unwanted alert text in the section Section: Loading and disabling confirm button > Show loading confirm modal
https://user-images.githubusercontent.com/62020972/213620799-c43a1ca7-b449-4f0e-89f9-9a67b53cde59.mov
#176 

 Removing message text in the examples section

---

src-docs/src/views/color_palette/color_palette_example.js

Removes the link that points to the elastic charts in the section color palettes.
#304 

[OUI Docs] Removed the link in the section ColorPalattes

---

src-docs/src/views/link/link.js
src-docs/src/views/link/link_validation.js

Updated the links to the Opensearch website in the Links section.
#210 

Updated link Validation section

---

src-docs/src/views/empty_prompt/custom.js
src-docs/src/views/empty_prompt/empty_prompt.js
src-docs/src/views/empty_prompt/empty_prompt_example.js
src-docs/src/views/empty_prompt/empty_prompt_loading.js
src-docs/src/views/empty_prompt/empty_prompt_states.js
src-docs/src/views/empty_prompt/playground.js
src-docs/src/views/empty_prompt/simple.js

Updated the content in the section Empty Prompt.
https://user-images.githubusercontent.com/62020972/218584367-e0107ccb-6571-4e3a-af06-e8f30d8455b7.mov
#246 

[OUI Docs] Updated the content for the Empty prompt

---

src/components/breadcrumbs/__snapshots__/breadcrumbs.test.tsx.snap
src/components/breadcrumbs/_breadcrumbs.scss
src/components/breadcrumbs/_variables.scss
src/components/breadcrumbs/breadcrumbs.tsx
src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
src/components/header/__snapshots__/header.test.tsx.snap
src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
src/themes/oui/oui_colors_dark.scss

Migrate breadcrumb style to OUI
#22 

Update breadcrumbs to new styling

---

src-docs/src/views/tables/in_memory/in_memory.js
src-docs/src/views/tables/in_memory/in_memory_controlled_pagination.js
src-docs/src/views/tables/in_memory/in_memory_search.js
src-docs/src/views/tables/in_memory/in_memory_search_callback.js
src-docs/src/views/tables/in_memory/in_memory_search_external.js
src-docs/src/views/tables/in_memory/in_memory_selection.js

Removed GitHub column from all the tables in the section in-memory tables.
https://user-images.githubusercontent.com/62020972/220445292-1a7af1cf-9ef1-4c57-80a4-cbc299999338.mov
#238 

[OUI Docs] Removed GitHub column from all the tables

---

src-docs/src/views/error_boundary/error_boundary.js

Updated the error text in the section ErrorBoundary.
#346 

[OUI Docs] Updated the text in the section ErrorBoundary

---

src-docs/src/views/expression/columns.js
src-docs/src/views/expression/stringing.tsx
src-docs/src/views/expression/truncate.js

Updated the Kibana references to opensearch dashboards in the section expression.
#287 

[OUI Docs] Deprecated kibana references

---

src-docs/src/views/beacon/beacon_example.js

Updated the section Beacon.
#340 

[OUI Docs] Updated the section Beacon

---

src-docs/src/views/guidelines/getting_started.md

https://github.com/opensearch-project/oui/issues/104

[Docs] Update getting_started.md to remove elastic reference and other changes

---

.github/workflows/release-drafter.yml

Add permissions to the workflow to release drafter workflow. 
Solution picked from GHA issues https://github.com/softprops/action-gh-release/issues/236

Add permissions to the workflow

---

src-docs/src/views/card/card.js
src-docs/src/views/card/card_beta.js
src-docs/src/views/card/card_children.js
src-docs/src/views/card/card_display.js
src-docs/src/views/card/card_example.js
src-docs/src/views/card/card_footer.js
src-docs/src/views/card/card_image.js
src-docs/src/views/card/card_layout.js
src-docs/src/views/card/card_selectable.js

Updated the content in the section Card by replacing icons, updating card titles, changing button labels, removing the "lens" card, and modifing the beta badge to use the "experimental" label.
Fixes #242 

Update content in the section Card

---

src-docs/webpack.config.js
src/webpack.config.js

Fix deprecated webpack configuration
https://github.com/opensearch-project/oui/issues/577

[CCI] Fix deprecated webpack configuration

---

README.md

This fix changes the logo linking, as it was leading to a non-existent file. Instead, it uses the logo asset that is stored externally on the OpenSearch website.
Closes #564

Readme Opensearch Logo linking to non-existent file [CCI]

---

src-docs/src/views/tool_tip/tool_tip_example.js

Changed `OuiTitle` size property to `m` in `tool_tip_example.js` file
https://github.com/opensearch-project/oui/issues/607

[CCI] Change OuiTitle size property to m in tooltip example

---

package.json
yarn.lock

1. `yo-doc` and `yo-component` scripts work
2. After removing `node_modules` there are no errors regarding `trim-newlines`
```
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
warning Resolution field "trim@0.0.3" is incompatible with requested version "trim@0.0.1"
[2/4] 🚚  Fetching packages...
warning Pattern ["gonzales-pe-sl@github:srowhani/gonzales-pe#dev"] is trying to unpack in the same destination "/Users/andreymyssak/Library/Caches/Yarn/v6/npm-gonzales-pe-sl-4.2.3/node_modules/gonzales-pe-sl" as pattern ["gonzales-pe-sl@^4.2.3"]. This could result in non-deterministic behavior, skipping.
[3/4] 🔗  Linking dependencies...
warning " > @elastic/eslint-config-kibana@0.15.0" has incorrect peer dependency "babel-eslint@^8.0.0".
warning " > @elastic/eslint-config-kibana@0.15.0" has …
```

[CCI] Fix yo-doc and yo-component crashes

---

src-docs/src/views/page/page.js
src-docs/src/views/page/page_bottom_bar_template.js
src-docs/src/views/page/page_centered_content_template.js
src-docs/src/views/page/page_custom_content_template.js
src-docs/src/views/page/page_restricting_width_template.js
src-docs/src/views/page/page_simple_empty_content_template.js
src-docs/src/views/page/page_template.js

Removed logos for the all examples in the section page.
Fixes #625 

Remove logos for page examples

---

src/components/loading/__snapshots__/loading_elastic.test.tsx.snap
src/components/loading/__snapshots__/loading_kibana.test.tsx.snap
src/components/loading/loading_elastic.test.tsx
src/components/loading/loading_elastic.tsx
src/components/loading/loading_kibana.test.tsx
src/components/loading/loading_kibana.tsx
src/utils/deprecated/__snapshots__/deprecated.test.tsx.snap
src/utils/deprecated/deprecated.test.tsx
src/utils/deprecated/deprecated.tsx
src/utils/deprecated/index.ts
src/utils/index.ts

Added deprecation comments to OuiLoadingElastic and OuiLoadingKibana
- Used JSDoc deprecated tag
- Added `deprecated` component to console deprecation warning
https://github.com/opensearch-project/oui/issues/266

[CCI] Add deprecation comments to OuiLoadingElastic and OuiLoadingKibana

---

.github/workflows/release-drafter.yml

Adds build artifacts to the release drafter workflow. By running `yarn build` before drafting the release, we can make sure releases include all of the compiled JS and CSS needed by consumers

Add build artifacts to release

---

jenkins/release.JenkinsFile

Depends on https://github.com/opensearch-project/oui/pull/636 and https://github.com/opensearch-project/opensearch-build-libraries/pull/177
Changes the way OUI is published to npmjs.org. See attached issue for more details. The dependent PRs need to go in first. Keeping it in draft till then.
closes https://github.com/opensearch-project/opensearch-build/issues/3312

Publish OUI to npmjs using tarball

---

package.json
src/components/markdown_editor/__snapshots__/markdown_editor.test.tsx.snap
yarn.lock

Update dropzone dependency to 14.2.3
https://github.com/opensearch-project/oui/issues/594

[CCI] Update dropzone dependency

---

package.json
src-docs/src/views/datagrid/additional_controls.js
src-docs/src/views/datagrid/column_actions.js
src-docs/src/views/datagrid/column_cell_actions.js
src-docs/src/views/datagrid/column_widths.js
src-docs/src/views/datagrid/container.js
src-docs/src/views/datagrid/control_columns.js
src-docs/src/views/datagrid/datagrid.js
src-docs/src/views/datagrid/focus.js
src-docs/src/views/datagrid/footer_row.js
src-docs/src/views/datagrid/in_memory.js
src-docs/src/views/datagrid/in_memory_enhancements.js
src-docs/src/views/datagrid/in_memory_pagination.js
src-docs/src/views/datagrid/in_memory_sorting.js
src-docs/src/views/datagrid/row_height_options.js
src-docs/src/views/datagrid/schema.js
src-docs/src/views/datagrid/styling.js
src-docs/src/views/datagrid/virtualization.js
src-docs/src/views/datagrid/virtualization_constrained.js
src-docs/src/views/image/float.js
src-docs/src/views/resizable_container/resizable_container_basic.js
src-docs/src/views/resizable_container/resizable_container_reset_values.js
src-docs/src/views/resizable_container/resizable_container_vertical.js
src-docs/src/views/resizable_container/resizable_panel_collapsible.js
src-docs/src/views/resizable_container/resizable_panel_collapsible_options.js
src-docs/src/views/resizable_container/resizable_panel_collapsible_responsive.js
yarn.lock

Migrate from `faker` to `@faker-js/faker`. 
The main goal is not to update `faker` as done in https://github.com/opensearch-project/oui/pull/653, but to discard it immediately and migrate to `@faker-js/faker`.
https://github.com/opensearch-project/oui/issues/594

[CCI] Migrate from faker to @faker-js/faker

---

scripts/postinstall.js

Previously, in https://github.com/opensearch-project/oui/commit/9abf87e5c5ffcf970d0b45c5fa7db0ea8f7c18df, there was an aliasing regression in `scripts/postinstall.js`. Essentially it didn't rename files to their EUI counterpart. This PR fixes that and prepares OUI for the 1.1 release

Fix aliasing regression in post install script

---

yarn.lock

Update loader-utils to 1.4.2. For some reason, it looks like 2.0.4 got backported but this version didn't. Fixes that.

Update loader-utils to 1.4.2

---

scripts/compile-oui.js
scripts/dtsgenerator.js
src-docs/src/theme_cascadia_dark.scss
src-docs/src/theme_cascadia_light.scss
src-docs/src/theme_dark.scss
src-docs/src/theme_light.scss

Removed unused chart theme code and imports
https://github.com/opensearch-project/oui/issues/656

[CCI] Remove unused chart theme code

---

yarn.lock

Bumps `sass-loader` to `10.4.1`. A little while ago, `node-sass` was upgraded to `8.0.0`, which was incompatible with `sass-loader`. This should fix the 1.1 version of the docsite.

Bump sass-loader to 10.4.1

---

src/components/bottom_bar/__snapshots__/bottom_bar.test.tsx.snap
src/components/bottom_bar/_bottom_bar.scss
src/components/bottom_bar/bottom_bar.tsx
src/components/page/__snapshots__/page_template.test.tsx.snap

Moved OuiBottomBar default inline styles to the CSS file
https://github.com/opensearch-project/oui/issues/693

[CCI] Move OuiBottomBar default inline styles to the CSS file

---

package.json
scripts/compile-clean.js
yarn.lock

Bump `rimraf` from 3.0.2 to 5.0.0. In version v5.0.0 there is no default export, only named export (see https://github.com/isaacs/rimraf/blob/main/CHANGELOG.md#50)
https://github.com/opensearch-project/oui/issues/594

[CCI] Bump rimraf from 3.0.2 to 5.0.0

---

src-docs/src/views/tables/actions/actions.js

Removed Elastic References from OuiBasicTable Actions examples
https://github.com/opensearch-project/oui/issues/697

[CCI] Remove Elastic References from OuiBasicTable

---

src/components/datagrid/data_grid.tsx
src/components/datagrid/data_grid_body.tsx

There is a bug with DataGrid component, when there is less number of rows with data than number of rows per page, the DataGrid component is rendered with height equal to number of rows per page, instead of number of actual rows. This results in an empty unused space. 
For example, when there is 99 rows but the number of rows is 120, the table is rendered with height that fits 120 rows, and not 99. Screenshot:
The issue is even more evident when we make number of rows per page even larger (e.g. 1000 per page). I explained more in the issue https://github.com/opensearch-project/oui/issues/699 where I provided a sandbox.
After fix:
You might notice that the rows per page is 99 in the screenshot (actual number of rows), but the options show 120 ( they usually are provided by the developer), …

[Data Grid] Fix logic when pageSize larger than number of rows

---

.github/workflows/github-workflow-badger.yml

Add github-merit-badger workflow, taken from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3721
https://github.com/opensearch-project/oui/issues/638

[CCI] Add github-merit-badger workflow

---

src/components/page/page_header/page_header.tsx
src/components/page/page_header/page_header_content.tsx

Deprecated ```iconType``` and ```iconProps``` as according to the https://github.com/opensearch-project/oui/issues/644 they will no longer be used/supported.
First (out of 2) PR to solve https://github.com/opensearch-project/oui/issues/644

Deprecate ```iconType``` and ```iconProps``` from ```OuiPageHeader```

---

src/components/breadcrumbs/_breadcrumbs.scss
src/components/breadcrumbs/breadcrumbs.tsx
src/components/header/__snapshots__/header.test.tsx.snap

Fixes breadcrumb styling when there is only a single breadcrumb.
Before:
After:
Fixes #771 

Fix breadcrumb styling with a single breadcrumb

---

src/components/combo_box/combo_box.tsx

Previously, if `isLoading` was set in `onFocus`, options wouldn't be added when they were clicked. The issue stemmed from `onFocus` not being removed from the list of props passed to the root element of combo box. Essentially, `onFocus` would be called twice, once from the root element and once from `OuiComboBoxInput`. This meant that if you clicked an option, the root element's `onFocus` would fire, cancelling the option selection.
This bug is super nuanced so if you need more context, I can add it. Basically, just taking it out of the `rest` object fixes the bug.
Fixes #696
For more information on following Developer Certificate of Origin and signing off your commits, …

Fix combo box onFocus bug

---

.github/CODEOWNERS
MAINTAINERS.md

Following the process in [`opensearch-project/.github/RESPONSIBILITIES.md`](https://github.com/opensearch-project/.github/blob/main/RESPONSIBILITIES.md#becoming-a-maintainer), I had nominated Andrey and Sergey Myssak (@andreymyssak and @SergeyMyssak) as co-maintainers. The maintainers have voted and agreed to this nomination.
---
I would like to nominate Sergey ([SergeyMyssak](https://github.com/SergeyMyssak) on Github) and Andrey ([andreymyssak](https://github.com/andreymyssak) on Github) as maintainers for OUI. They have made numerous contributions to OUI, including but not limited to helping fix issues in backports (https://github.com/opensearch-project/oui/pull/757), auditing usage of outdated dependencies and creating action items to remedy …

Add @andreymyssak and @SergeyMyssak as co-maintainers

---

FAQ.md
scripts/deploy/deploy_docs
scripts/update-changelog-version.js
src-docs/src/views/datagrid/datagrid_example.js
src-docs/src/views/guidelines/sass.js
src-docs/src/views/home/home_view.js
src-docs/src/views/package/changelog.js
src-docs/src/views/package/i18n_tokens.js
src-docs/src/views/tool_tip/tool_tip_example.js
wiki/documentation-guidelines.md

The current default branch is `main`. I have updated the places that still refer to `master`.
Before:
After:
https://github.com/opensearch-project/oui/issues/797

[CCI] Update the default branch

---

src/components/suggest/_suggest_item.scss
src/global_styling/css_variables/_fonts.scss
src/global_styling/css_variables/_index.scss
src/global_styling/index.scss
src/global_styling/mixins/_typography.scss
src/global_styling/reset/_reset.scss
src/global_styling/variables/_typography.scss

Replace usage of `$ouiFontFamily` and `$ouiCodeFontFamily` with `--oui-font-family` and `--oui-code-font-family` CSS variables

Make font consumption happen using CSS variables

---

.npmignore
.sass-lint.yml
package.json
scripts/preinstall.js

This change allows OUI to self-clean while being installed during development when linked to as a dependency.
Also:
* Fixed linting of sass files

Enable local consumption of OUI

---

src-docs/src/views/combo_box/combo_box_custom_icon.js
src-docs/src/views/combo_box/combo_box_default_icon.js
src-docs/src/views/combo_box/combo_box_example.js

Added props and examples for the combo box.
Fixes #98 

Add props and examples for the combobox

---

src-docs/src/views/combo_box/clear_on_blur.js
src-docs/src/views/combo_box/combo_box_example.js
src-docs/src/views/combo_box/combo_box_icon.js

Add docs for icon and revise example for clearOnBlur for the combo box
#98 

[OuiComboBox] Add docs for icon and revise example for clearOnBlur

---

src/components/text/_text.scss
src/theme_dark.scss
src/theme_light.scss
src/themes/oui-cascadia/global_styling/mixins/_button.scss
src/themes/oui-cascadia/global_styling/mixins/_typography.scss
src/themes/oui-cascadia/global_styling/variables/_colors.scss
src/themes/oui-cascadia/global_styling/variables/_typography.scss
src/themes/oui-cascadia/oui_cascadia_colors_dark.scss

Includes:
* Introduce the new color palette
* Revert `$ouiLinkColor` to match `$ouiColorPrimaryText`
* Update fonts to "Source Sans 3" and "Source Code Pro"
* Remove font override from `.ouiText blockquote`
* To maintain the previous look in the `default` theme, the rule was added as an override there
* Set ouiButton font weight to semi-bold
* Remove negative `letter-spacing` from default font
* To prevent changes in `OuiTitle` in the default theme, the variants that inherited their `letter-spacing` were modified to explicitly have the old value.
For more information on following Developer Certificate of Origin and signing off your …

[New Theme] Introduce the first installment of the new look and feel

---

src/components/markdown_editor/plugins/markdown_default_plugins.tsx

This PR disables emoticons (`x-p`, `8)`, etc.) by default but still allows emojis through something like `:laughing:`
#802 

Disable emoticon in markdown renderer by default

---

CHANGELOG.md

Adds 1.1.0 release changes to changelog. These changes were gotten from this diff: https://github.com/opensearch-project/oui/compare/1.0...1.1
Question to reviewers: I think we're changing which branches we're going to be backporting to, so should this be backported to `1.x` as well as `1.1`, or just `1.x`?

Update changelog with 1.1 info

---

src-docs/src/views/app_view.js
src-docs/src/views/page/page_bottom_bar.js
src-docs/src/views/page/page_centered_content.js
src-docs/src/views/page/page_restricting_width.js

`OuiPageBody` has a `panelled` prop, but most OpenSearch Dashboard layouts don't use it, so it makes sense for the OUI documentation website to match that general behavior.
Example of old layout (panelled):
Updated (not-panelled):
Fixes https://github.com/opensearch-project/oui/issues/840

Remove all doc site usages of 'panelled' prop in OuiPageBody components

---

scripts/preinstall.js

Adds deps to keep for deps that are needed in a local OUI Dashboards setup. Also removes `@types/react`, as it causes type errors in Dashboards with differently typed versions of React.

Change deps to keep in preinstall script

---

scripts/compile-oui.js
scripts/dtsgenerator.js
src-docs/src/theme_dark.scss
src-docs/src/theme_light.scss
src-docs/src/theme_next_dark.scss
src-docs/src/theme_next_light.scss
src-docs/src/views/markdown_editor/markdown_editor_with_plugins.js
src/themes/charts/theme.scss
src/themes/charts/themes.ts

[2086980](https://github.com/opensearch-project/oui/commit/20869800a42d1f658b3a2d4bde4d9a7a4df13296) and [e9a63af](https://github.com/opensearch-project/oui/commit/e9a63afd05e4bb532f30fd9359a71704e15a8ded) have been reverted to not break integrations with OpenSearch Dashboards.
https://github.com/opensearch-project/oui/issues/810

[CCI] Revert changes to chart themes

---

.github/workflows/changelog_verifier.yml

Add `autocut` label to changelog verifier skip label set. We know whether or not a PR should have a changlog when it's created, but don't want to need to add the `skip-changelog` label to backports if their original PR had it. This just ignores all backport PRs because they should theoretically have already had the check pass.

Add autocut label to changelog verifier skip

---

CHANGELOG.md
src/global_styling/mixins/_form.scss
src/themes/oui-next/global_styling/mixins/_form.scss

Input fields that are auto-populated by the browser, like a saved usernames, are too dark to see in the dark mode for both default and Next themes. That is because the "shades" are reversed in dark mode where `$ouiColorLightestShade` is in fact nearly black and `$ouiColorDarkestShade` is nearly while. This change makes use of `$ouiColorDarkestShade` in both light and dark themes.
Before change:
After change:
Fixes #870

Fix `autofill` text color in dark themes

---

CHANGELOG.md
src-docs/src/views/collapsible_nav/collapsible_nav_list.tsx
src-docs/src/views/header/header_dark.tsx

For validating new theme colors, it's helpful to be able to quickly test out component props that affect color selection (on top of the application theme).
1. Add `theme` prop toggle to Header
2. Add `background` prop selector to Collapsible Nav
https://github.com/opensearch-project/oui/assets/1679762/5cb32852-165c-40f7-8395-e7c4723b8ec8

Doc Site - Add dark prop toggles

---

CHANGELOG.md
src/components/breadcrumbs/_breadcrumbs.scss
src/components/breadcrumbs/_variables.scss
src/themes/oui-next/oui_next_colors_dark.scss
src/themes/oui/oui_colors_dark.scss

Fix blurry text in breadcrumbs by using `:before` pseudoelement. Also took this opportunity to make breadcrumb colors come from theme. All accessibility checks pass.
**Current light**
**Current dark**
**Next light**
**Next dark**
Mostly/completely fixes #902

Fix blurry breadcrumb text

---

CHANGELOG.md
src/components/link/_mixins.scss

Set link to use semi bold font weight to add more visual distinction from the text around it
**Before**
**After**
Fixes #933

Set link to use semi bold font weight

---

CHANGELOG.md
package.json
yarn.lock

Bumps `node-sass` to a version that uses `libsass@3.6.5` as the original deprecated one is based on vulnerable `libsass@3.5.5`.

Bump `node-sass` to a version based on `libsas@3.6.5`

---

CHANGELOG.md
src/themes/oui-next/global_styling/variables/_colors.scss

Update next light theme primary color to #07827E to work better with the color system
Fixes #979

Update next light theme primary color to #07827E

---

CHANGELOG.md
src/components/schema/_schema_item.scss

`calc()` is not parsed by libsass and shouldn't be used for build-time mathematics.

Remove `calc` usage from SchemaItem styles

---

CHANGELOG.md
src-docs/src/views/form_validation/form_validation_example.js

Removed the line `You can also hide the callout by passinginvalidCallout=“none“` as described in issue #885
Closes #885 

(OUI Docs) Update Form validation page

---

CHANGELOG.md
src-docs/src/views/call_out/info.js
src/components/call_out/__snapshots__/call_out.test.tsx.snap
src/components/call_out/_call_out.scss
src/components/call_out/call_out.test.tsx
src/components/call_out/call_out.tsx

Add optional prop `dismissible` to `OuiCallOut`. 
https://github.com/opensearch-project/oui/assets/43937633/9866d59a-c420-4976-910a-c55f17317b15
resolves #881 

Add dismissible prop to OuiCallOut

---

CHANGELOG.md
src/themes/oui-next/global_styling/variables/_tool_tip.scss

Use `#293847` in `next` theme. Keep current theme tooltips the same.
https://github.com/opensearch-project/oui/assets/1679762/4d0cac30-9689-4071-b2ac-ccf33fab6f0a
Fixes #953 

Adjust background color of `OuiToolTip`

---

src-docs/src/views/call_out/info.js
src/components/call_out/__snapshots__/call_out.test.tsx.snap
src/components/call_out/call_out.test.tsx
src/components/call_out/call_out.tsx

Rename onDismissible prop to onDismiss.

Rename onDismissible to onDismiss for OuiCallOut

---

CHANGELOG.md
src/themes/oui-next/global_styling/variables/_form.scss

Set to `#293847` for better contrast against both page background and panel background
Definitions for other themes and modes remain the same
https://github.com/opensearch-project/oui/assets/1679762/efb0694e-f21c-41e9-8e84-08dda16b7011
Fixes #939

Adjust `$ouiFormInputGroupLabelBackground color` in dark `next` theme

---

CHANGELOG.md
src/components/collapsible_nav/_collapsible_nav.scss
src/global_styling/variables/_collapsible_nav.scss
src/themes/oui-next/global_styling/variables/_collapsible_nav.scss

`OuiCollapsibleNav` is a wrapper of `OuiFlyout`, but in the next theme, we want to have a different background styling by default. We introduce a new theme variable that's only set in the `next` theme.
In current theme, background should still come from OuiFlyout default styling
From: https://oui.opensearch.org/1.2/#/navigation/collapsible-nav/collapsible-nav-all
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4878

Override OuiCollapsibleNav background color in `next` theme

---

CHANGELOG.md
src-docs/src/views/guidelines/_get_sass_vars.js

Fix issue where Next Light theme color guidelines would come up with current Light color guidelines. Set it to retrieve the colors from the correct place.

Fix next light color guidelines

---

CHANGELOG.md

Update changelog for 1.3 release. Will update on 1.3 and 1.x branches manually.

Update changelog for 1.3 release

---

CHANGELOG.md
src-docs/src/views/list_group/list_group_extra.js
src/components/list_group/_list_group_item.scss

Fix alignment of left icon for OuiListGroupItem with multiline text
**Before:**
**After:**
Fixes #1000

Fix alignment of left icon for OuiListGroupItem

---

CHANGELOG.md
scripts/compile-scss.js

Add exit code to compile-scss script on failure. Previously, if this script had an error, it wouldn't propagate, which would cause false positives in our CI workflows.

Add exit code to compile-scss script on failure

---

CHANGELOG.md
package.json
yarn.lock

Update `caniuse` db, and reorder package.json dev dependencies. It seems somehow these got out of order at some point, so whenever we update that package.json, this reordering will happen.
Kinda curious if we can do this update automatically...

Update caniuse db

---

package.json
scripts/compile-clean.js
yarn.lock

After merging the Typescript update, there was a bug that popped up when trying to start the docsite. Essentially, the docgen info wasn't being generated. This is because the `react-docgen-typescript` package used a Typescript API that apparently broke in one of the versions between what we updated from and to. Updating that package fixes the issue.

Fix docgen babel plugin

---

CHANGELOG.md
src/components/search_bar/filters/field_value_selection_filter.tsx
src/components/search_bar/filters/field_value_toggle_filter.tsx
src/components/search_bar/filters/field_value_toggle_group_filter.tsx
src/components/search_bar/filters/is_filter.tsx
src/components/search_bar/search_bar.tsx

This change clarifies the file path for the Query export in five files. Before the change, the OUI documentation site was not loading on my browser, and the console displayed the warnings in the following screenshot:
After the change, the documentation site loads successfully, and the warnings regarding the Query export are absent from my console:
Fixes issue [#1063](https://github.com/opensearch-project/oui/issues/1063) 

[OSCI] Bug fix: Correct file path for importing Query component

---

CHANGELOG.md
package.json

Changed ```pre-commit``` hook to only use ```yarn lint``` instead of using ```test-staged``` script. 
Changed ```test-staged``` script by removing ```yarn lint``` from it.
solves issue #1070 

Made recommended changes to git pre-commit hook

---

CHANGELOG.md
i18ntokens.json
package.json
src/components/tabs/tabbed_content/tabbed_content.tsx
yarn.lock

Bump `@types/react` and `csstype`
* These are needed to be kept in sync with OSD's.
* Switch `css-loader` to an alternate to match that of OSD's, just in case.

Bump `@types/react` and `csstype`

---

wiki/consuming.md

This change fixes a simple typo in `wiki/consuming.md`.
Because this was a simple spelling error, I did not raise a dedicated issue for it.

[OSCI] Fix Typo in `wiki/consuming.md`

---

CHANGELOG.md
src-docs/src/views/guidelines/colors/_utilities.js
src-docs/src/views/guidelines/colors/color_section.js
src-docs/src/views/guidelines/colors/core_palette.js
src-docs/src/views/guidelines/colors/vis_palette.js
src-docs/src/views/guidelines/sass.js

Resolve the issue where the Source Documentation would render blank pages when users clicked on either the "Colors" or "Sass" sections.
Closes #1109 
https://github.com/opensearch-project/oui/assets/65143821/8f09f867-b4f0-411f-aa1c-b147810405f1
https://github.com/opensearch-project/oui/assets/65143821/8ecd4720-4751-4221-ba0e-228354ac9bb5

[Fix] "Guidelines" Documentation Render Blank Page

---

CHANGELOG.md
scripts/test-staged.js

- Add error handling when stagedFiles are empty
Closes #1071
- OUI Version: 1.3.0
- OS: macOS Sonoma 14.0

[Fix] Add error handling when staged files are empty

---

CHANGELOG.md
src/components/tree_view/tree_view.scss

Removes max height for Oui TreeView node
Fixes #1118

[BUG] Tree view expanded view #1118

---

.github/workflows/build_and_test.yml
CHANGELOG.md

Skip depedabot PR runs on push. This prevents duplicated runs in dependabot PRs, as they run on PR as well.

Skip build and test on dependabot

---

CHANGELOG.md
src/global_styling/mixins/_helpers.scss
src/themes/oui-next/global_styling/mixins/_helpers.scss

Eliminate the extra "Row # Column #" when selecting data grid table and pasting.
resolves https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5570

Eliminate screenreader content when copying and pasting data grid table

---

CHANGELOG.md
src/components/suggest/_suggest_item.scss
src/themes/oui-next/global_styling/mixins/_typography.scss
src/themes/oui-next/global_styling/reset/_reset.scss
src/themes/oui-next/global_styling/variables/_typography.scss

Since the text font for the Next theme has a smaller appearance, a larger font-size is employed.
PS, this will probably need some followups to fine tune other areas.

[Next Theme] Set base font size to 18px

---

CHANGELOG.md
src/themes/oui-next/global_styling/mixins/_button.scss

[Next Theme] Revert `font-weight` of OuiButton to normal from semi-bold
* The larger font-size eliminates the need for bolder text

[Next Theme] Revert `font-weight` of OuiButton to normal from semi-bold

---

CHANGELOG.md
src/components/resizable_container/_resizable_collapse_button.scss

Prevent collapsable button of a resizable from adding to the height when hidden

Prevent collapsable button of a resizable from adding to the height when hidden

---

CHANGELOG.md
src/components/datagrid/_data_grid_data_row.scss

Prevent action buttons of OuiDataGridCell from moving the content

Prevent action buttons of OuiDataGridCell from moving the content

---

yarn.lock

Manually bumped a failed backport of #1200
Will manually add to the changelog

[CVE-2023-26159] Bump `follow-redirects` to 1.15.5

---

.sass-lint.yml
CHANGELOG.md
src/services/color/oui_palettes.ts
src/themes/oui-next/oui_next_colors_dark.scss
src/themes/oui/oui_colors_dark.scss

Shorthand colors are not handled by nested deps and as a result we need to force all colors to be full hexes.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6243

Convert shorthand palette colors to full 6-char hex

---

CHANGELOG.md
yarn.lock

Bump tar from 6.1.11 to 6.2.1
cherry picked 068d41da74d84cb43e218e3825be4b1206cb1d60 from #1260
Bump follow-redirects from 1.15.4 to 1.15.6
cherry picked 8b9325e8e04a3436677ad56c8987ff116a6cc9c5 from #1258

[Backport 1.x] Bump tar and follow-redirects

---

CHANGELOG.md
src/components/context_menu/_context_menu_panel.scss
src/components/tool_tip/_tool_tip.scss
src/global_styling/mixins/_popover.scss
src/themes/oui-next/global_styling/mixins/_popover.scss

Adjusts popover/context menu titles to use normal casing, for small context menus to use normal font size to match popovers, and for tooltips to be forced to small size (padding and font size).
| Item |  Before (v7dark) | After (v7dark) | Before (v8dark) | After (v8dark) |
| ---- | ---- | ---- | ---- | ---- | 
| Popover |![image](https://github.com/opensearch-project/oui/assets/1366272/fbdf8eb8-f36b-42a1-8418-7388cf5a1a10) | ![image](https://github.com/opensearch-project/oui/assets/1366272/f87dd23b-a8f4-42e5-a339-2eb521d09b28)|![image](https://github.com/opensearch-project/oui/assets/1366272/3ed771da-eaed-43f9-bd0d-d216aed1b16f) | ![image](https://github.com/opensearch-project/oui/assets/1366272/8b0c0e82-bd8f-457a-8da9-75907fca1633)|
| Context Menu | …

feat: adjust popover and context menu title styles and tooltip padding

---

CHANGELOG.md
src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
src/components/date_picker/super_date_picker/super_update_button.tsx

Makes the Update/Refresh button in SuperUpdateButton secondary instead of primary.
| Before | After |
| ---- | ---- |
| ![image](https://github.com/opensearch-project/oui/assets/1366272/804e6696-d908-4e75-abec-8297d766883f)| ![image](https://github.com/opensearch-project/oui/assets/1366272/03f11965-7316-4f04-8a60-6a8a9891f706) |
N/A

feat: make SuperUpdateButton's button secondary

---

CHANGELOG.md
src/components/modal/_modal.scss
src/components/popover/_popover.scss
src/components/tool_tip/_tool_tip.scss
src/global_styling/mixins/_tool_tip.scss
src/themes/oui-next/global_styling/mixins/_tool_tip.scss

Increase animation speed/behavior for modals, popovers, and tooltips
| Component | Before | After |
| ---- | ---- | ---- |
| Modals |![modal before](https://github.com/opensearch-project/oui/assets/1366272/d6b62a85-19b3-4383-b4ca-bd26d79dab66) | ![modal after](https://github.com/opensearch-project/oui/assets/1366272/fbe5d797-18f8-47af-86e1-5ca010025bd3)| 
| Popovers |![popover before](https://github.com/opensearch-project/oui/assets/1366272/ed4e1546-9b00-405e-9195-e6af54c5ecbf) | ![popover after](https://github.com/opensearch-project/oui/assets/1366272/056df2cc-d611-48dc-ac2f-447d904d44a9)| 
| Tooltips |![tooltip before](https://github.com/opensearch-project/oui/assets/1366272/71d7d9c7-3abb-4062-b681-77f878098fc4)| ![tooltip after](https://github.com/opensearch-project/oui/assets/1366272/a …

feat: use faster animations for modals, popovers, and tooltips

---

CHANGELOG.md
src/components/button/button_group/_button_group_button.scss
src/global_styling/mixins/_button.scss
src/themes/oui-next/global_styling/mixins/_button.scss

Sets font-size of buttons to use small font size by default, making the font size of buttons consistent across all buttons, and consistent across input sizes which they're commonly aligned with.
| Type | Before (v7light) | After (v7light) | Before (v8dark) | After (v8dark) |
| ------------- | ------------- | ------------- |  ------------- | ------------- |
| Normal |![image](https://github.com/opensearch-project/oui/assets/1366272/b06e89d1-8847-4dd4-8cc1-c6c79ddc1921) | ![image](https://github.com/opensearch-project/oui/assets/1366272/96d7eba9-9b96-4cdc-a0ec-e743905a9425)| ![image](https://github.com/opensearch-project/oui/assets/1366272/308048a2-5b05-4312-a1ea-fd8aa83db465) | ![image](https://github.com/opensearch-project/oui/assets/1366272/3a89f2f4-7433-4ece-aa4e-37a9babd9951)  |
| …

feat: use consistent font sizes in buttons

---

CHANGELOG.md
src/components/button/_button.scss
src/components/button/button_icon/_button_icon.scss
src/components/split_button/_split_button_control.scss
src/global_styling/mixins/_button.scss
src/global_styling/mixins/_shadow.scss
src/themes/oui-next/global_styling/mixins/_button.scss
src/themes/oui-next/global_styling/mixins/_shadow.scss

To avoid buttons physically moving, we've removed the translations on hover/focus and replaced it with an inset shadow (with existing removal of focus/active shadow). We will likely change/refine this behavior in the future, but this removes the weirdness of a physically moving button.
I changed the implementation of ouiSlightShadowActive because there were no active consumers in OUI or OpenSearch Dashboards.
The main downsides of this approach are when background is black and the button is white or a button icon without a border as these cases won't have a super visible change on active.
| Item |  Before (v7dark) | After (v7dark) | Before (v8dark) | After (v8dark) |
| ---- | ---- | ---- | ---- | ---- | 
| Button | ![button v7 before](https://github.com/opensearch-project/oui/assets/136627 …

feat: remove Button translations and add inset shadow on active

---

src-docs/src/views/link/link.js

This PR updates the documentation to include a clearer explanation of the `external` prop in the `OuiLink` component. The modification explicitly describes the automatic rendering of a `pop-out` icon when the external prop is set to true, enhancing the documentation's clarity.
See the discussion here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5511

[Enhance] Add Explanation for external Prop in OuiLink

---

CHANGELOG.md
src/components/date_picker/super_date_picker/quick_select_popover/__snapshots__/quick_select_popover.test.tsx.snap
src/components/date_picker/super_date_picker/quick_select_popover/quick_select_popover.tsx

This just makes the quickselectpopover in superdatepicker use small padding
| Before | After|
| ---- | ---- |
| <img width="444" alt="image" src="https://github.com/user-attachments/assets/fa72ac5b-4cd0-45b7-bcf6-5f8d56dc3f9c">| <img width="431" alt="image" src="https://github.com/user-attachments/assets/9041f018-f607-4192-b52c-e266d141f9f5">|
N/A

fix: Make QuickSelectPopover padding small in SuperDatePicker

---

CHANGELOG.md
src-docs/src/views/super_date_picker/super_date_picker_config.js
src/components/date_picker/date_picker_range.tsx
src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
src/components/date_picker/super_date_picker/_super_date_picker.scss
src/components/date_picker/super_date_picker/date_popover/_date_popover_button.scss
src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
src/components/date_picker/super_date_picker/super_date_picker.tsx
src/components/date_picker/super_date_picker/super_update_button.tsx

Cherry-picked c3c02d57349e4e1150abbc26f6cda5620de76957 from #1307

[Manual backport 1.8] Introduce compressed appearance for OuiSuperDatePicker (#1307)

---

CHANGELOG.md
src-docs/src/views/super_date_picker/super_date_picker_config.js
src/components/date_picker/date_picker_range.tsx
src/components/date_picker/super_date_picker/__snapshots__/super_date_picker.test.tsx.snap
src/components/date_picker/super_date_picker/__snapshots__/super_update_button.test.tsx.snap
src/components/date_picker/super_date_picker/_super_date_picker.scss
src/components/date_picker/super_date_picker/date_popover/_date_popover_button.scss
src/components/date_picker/super_date_picker/date_popover/date_popover_button.tsx
src/components/date_picker/super_date_picker/super_date_picker.tsx
src/components/date_picker/super_date_picker/super_update_button.tsx

Backport c3c02d57349e4e1150abbc26f6cda5620de76957 from #1307

[Manual backport 1.x] Introduce compressed appearance for OuiSuperDatePicker (#1307)

---

CHANGELOG.md
src/components/date_picker/super_date_picker/date_popover/date_popover_content.tsx

Makes the now button in SuperDatePicker secondary
Before:
After:
N/A

fix: Fix now button to be secondary in SuperDatePicker

---

CHANGELOG.md
src/components/form/switch/__snapshots__/switch.test.tsx.snap
src/components/form/switch/_switch.scss
src/components/form/switch/index.ts
src/components/form/switch/switch.tsx
src/global_styling/variables/_form.scss
src/themes/oui-next/global_styling/variables/_form.scss

Add display type and color to OuiSwitch
* `color` makes OuiSwitch colorable like OuiButton
* `display` allows showing a border around the switch like OuiButtonIcon

Add display type and color to OuiSwitch

---

CHANGELOG.md
src/components/combo_box/_combo_box.scss

Fixes the height of combo box with appended items. Whenever an append flag is added to single select combo box, the element height increases from 40px to 42px or even 43.33px based on the type of the item appended. This PR keeps the height of all combo box variants to 40px
Prior to fix: 
ed
Post fix all the combo boxes are on same height of 40px (non compressed) and 32px (compressed)

Fixes combobox height with appendees

---

CHANGELOG.md
src/components/button/button_empty/_button_empty.scss
src/components/date_picker/super_date_picker/quick_select_popover/_quick_select_popover.scss

Update styling for empty button and date picker icon alignments issues: 
```
to the left of the search bar is the save icon. it feels 1px lower than middle and 1px left of center.
```
* Enables button icon to be in right line-height based. 
* Reduces the spacing in between calendar button and pop over icon in super date picker
Before: 
After:

Update styling for empty button and date picker icon

---

CHANGELOG.md
package.json
yarn.lock

Fix docs error when accessing some props of some elements like OuiButton.

Fix docs error when accessing some props

---

CHANGELOG.md
src/global_styling/mixins/_typography.scss
src/global_styling/variables/_typography.scss
src/themes/oui-next/global_styling/mixins/_typography.scss
src/themes/oui-next/global_styling/variables/_typography.scss
src/themes/v9/global_styling/mixins/_typography.scss
src/themes/v9/global_styling/variables/_typography.scss

Introduce `$ouiLegibilityMaxWidth` variable and `ouiLegibilityMaxWidth` mixin

Introduce `$ouiLegibilityMaxWidth` variable and `ouiLegibilityMaxWidth` mixin

---

CHANGELOG.md
src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
src/components/button/__snapshots__/button.test.tsx.snap
src/components/button/button.test.tsx
src/components/button/button.tsx
src/components/button/button_content.tsx
src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
src/components/button/button_empty/button_empty.test.tsx
src/components/button/button_empty/button_empty.tsx
src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
src/components/split_button/__snapshots__/split_button.test.tsx.snap
src/global_styling/mixins/_button.scss
src/global_styling/variables/_size.scss
src/themes/oui-next/global_styling/mixins/_button.scss
src/themes/oui-next/global_styling/variables/_size.scss
src/themes/v9/global_styling/mixins/_button.scss
src/themes/v9/global_styling/variables/_size.scss

Add button icon gap prop

---

CHANGELOG.md
package.json
src/components/basic_table/__snapshots__/in_memory_table.test.tsx.snap
src/components/button/__snapshots__/button.test.tsx.snap
src/components/button/button.test.tsx
src/components/button/button.tsx
src/components/button/button_content.tsx
src/components/button/button_empty/__snapshots__/button_empty.test.tsx.snap
src/components/button/button_empty/button_empty.test.tsx
src/components/button/button_empty/button_empty.tsx
src/components/control_bar/__snapshots__/control_bar.test.tsx.snap
src/components/split_button/__snapshots__/split_button.test.tsx.snap
src/global_styling/mixins/_button.scss
src/global_styling/variables/_size.scss
src/themes/oui-next/global_styling/mixins/_button.scss
src/themes/oui-next/global_styling/variables/_size.scss
src/themes/v9/global_styling/mixins/_button.scss
src/themes/v9/global_styling/variables/_size.scss

cherry picked from commit 7bdea7afd9874e3c1b5ad75e5beb62763dcc7fe7 from #1367
Also:
* Bumped package version to the next release

Allow controlling the gap between the icon and the content of OuiButton and OuiButtonEmpty (#1367)

---

CHANGELOG.md
src/components/combo_box/_combo_box.scss
src/components/combo_box/combo_box_input/_combo_box_pill.scss
src/components/form/form_control_layout/_form_control_layout.scss

Fix combobox appearance when compressed, with pills, and in group
Also:
* Adjust prepend and appends in form layouts

Fix combobox appearance when compressed and in-group

---

CHANGELOG.md
i18ntokens.json
src/components/breadcrumbs/__snapshots__/breadcrumbs_simplified.test.tsx.snap
src/components/breadcrumbs/_breadcrumbs_simplified.scss
src/components/breadcrumbs/_index.scss
src/components/breadcrumbs/breadcrumbs.tsx
src/components/breadcrumbs/breadcrumbs_simplified.test.tsx
src/components/breadcrumbs/breadcrumbs_simplified.tsx
src/components/breadcrumbs/index.ts
src/components/header/header_breadcrumbs/__snapshots__/header_breadcrumbs.test.tsx.snap
src/components/header/header_breadcrumbs/_header_breadcrumbs.scss
src/components/header/header_breadcrumbs/header_breadcrumbs.test.tsx
src/components/header/header_breadcrumbs/header_breadcrumbs.tsx
src/components/index.js

Create OuiSimplifiedBreadcrumbs and update OuiHeaderBreadcrumbs

Create OuiSimplifiedBreadcrumbs and update OuiHeaderBreadcrumbs

---

CHANGELOG.md
src/components/button/_button.scss
src/components/button/button_group/_button_group.scss
src/components/button/button_icon/_button_icon.scss
src/components/date_picker/super_date_picker/_super_date_picker.scss
src/components/form/switch/_switch.scss
src/components/split_button/_split_button_control.scss
src/global_styling/mixins/_button.scss
src/themes/oui-next/global_styling/mixins/_button.scss
src/themes/v9/global_styling/mixins/_button.scss
src/themes/v9/global_styling/mixins/_form.scss
src/themes/v9/global_styling/reset/_reset.scss
src/themes/v9/global_styling/variables/_buttons.scss
src/themes/v9/global_styling/variables/_colors.scss
src/themes/v9/v9_colors_dark.scss

This makes updates to the v9 theme, including:
- Adding dark theme colors
- Adjusting existing link colors to match primary colors
- Removing shadows from inputs/buttons by defalt
- Adding shows on hover for inputs
- Correcting super date picker to use primary text color instead of link color to match empty button usage
| Item | Screenshot (v9) |  Screenshot (v7) |
| ---- | ---- | ---- |
| Super Date Picker|<img width="635" alt="image" src="https://github.com/user-attachments/assets/6895682d-fcba-4ef3-bd6b-0d01cb632687"> |<img width="612" alt="image" src="https://github.com/user-attachments/assets/4259ddbd-a96a-4867-b61b-8be05bc56999">|
| Form Components (default) |<img width="419" alt="image" src="https://github.com/user-attachments/assets/e0504629-ec40-4c50-b973-a4422d51bf81"> | |
| …

fix: Updates to v9 colors, button/input styles, and typography

---

CHANGELOG.md
package.json
src/components/button/_button.scss
src/components/button/button_group/_button_group.scss
src/components/button/button_icon/_button_icon.scss
src/components/date_picker/super_date_picker/_super_date_picker.scss
src/components/form/switch/_switch.scss
src/components/split_button/_split_button_control.scss
src/global_styling/mixins/_button.scss
src/themes/oui-next/global_styling/mixins/_button.scss
src/themes/v9/global_styling/mixins/_button.scss
src/themes/v9/global_styling/mixins/_form.scss
src/themes/v9/global_styling/reset/_reset.scss
src/themes/v9/global_styling/variables/_buttons.scss
src/themes/v9/global_styling/variables/_colors.scss
src/themes/v9/v9_colors_dark.scss

Backport of https://github.com/opensearch-project/oui/pull/1373 to 1.x + update to package.json and Changelog for new oui version
N/A

[Backport-1.x] fix: Updates to v9 colors, button/input styles, and typography (#1373)

---

CHANGELOG.md
src/components/search_bar/__snapshots__/search_bar.test.tsx.snap
src/components/search_bar/search_bar.tsx

Consume the `className` prop in OuiSearchBar
Also:
* deprecate `aria-label` and `data-test-subj` which have never been consumed despite being defined
Fixes #1343

Consume the `className` prop in OuiSearchBar

---

CHANGELOG.md
src/global_styling/variables/_responsive.scss
src/themes/oui-next/global_styling/variables/_responsive.scss
src/themes/v9/global_styling/variables/_responsive.scss

Expand definition of `$ouiBreakpoints` to include `xxl` and `xxxl`

Expand definition of `$ouiBreakpoints` to include `xxl` and `xxxl`

---

CHANGELOG.md
src-docs/src/views/text/text.js
src-docs/src/views/text/text_small.js
src/components/text/_text.scss
src/themes/v9/global_styling/variables/_typography.scss

Also:
* Adjust sizing of headers in v9
* bump up the sizing of `$ouiFontSizeS` and `$ouiFontSizeXS`

Remove scaling of heading elements

---

CHANGELOG.md
src-docs/src/views/tables/in_memory/in_memory_search.js
src/components/basic_table/in_memory_table.tsx

Make the space between search bar and table rows match the compressed state of the search box

Make the space between search bar and table rows match the compressed state of the search box

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Move Iskander, Andrey, and Sergey to the Emeritus list

Move Iskander, Andrey, and Sergey to the Emeritus list

---

src/themes/v9/global_styling/variables/_colors.scss
src/themes/v9/v9_colors_dark.scss

Just updates primary action color of v9 light theme, and fixing success color to match spreadsheet
N/A
- skip

fix: update v9 light primary color

---

jenkins/release.JenkinsFile

This change uses the GitHub tag used to release an artifact to tag the release on npmjs.org as well. As of now everything is mark latest as default which is not right. `beta` should be tagged as beta and same goes for other tags such as `rc`, `alpha`, etc. 
See https://github.com/opensearch-project/opensearch-build-libraries/releases/tag/6.9.0
This version parses the github tag and accordingly uses it in while publishing to npmjs.org

Upgrade build-lib version in release pipeline to accomodate new changes

---

CHANGELOG.md
i18ntokens.json
src-docs/src/views/guidelines/colors/_color_section.scss
src/components/header/header_links/header_links.test.tsx
src/components/page/page_header/_page_header_content.scss
src/components/page/page_side_bar/_page_side_bar.scss
src/components/page/page_template.tsx
src/components/search_bar/_search_bar.scss
src/components/table/_responsive.scss
src/components/table/_table.scss
src/global_styling/mixins/_header.scss
src/themes/oui-next/global_styling/mixins/_header.scss
src/themes/v9/global_styling/mixins/_header.scss

When we [added new breakpoints](https://github.com/opensearch-project/oui/commit/b8a9daa3edc9e6af0b4b07ef5b6a19a5b4410cd3), we didn't update components to utilize them, leading to some bugs. This just treats new breakpoints like xl out of an abundance of caution.
N/A

fix: Update components to respect new breakpoints

---

CHANGELOG.md
i18ntokens.json
src-docs/src/views/card/card_example.js
src-docs/src/views/panel/panel_color.js
src-docs/src/views/panel/panel_example.js
src/components/button/_button.scss
src/components/button/button_group/_button_group.scss
src/components/card/card.tsx
src/components/form/form_control_layout/_form_control_layout.scss
src/components/link/_mixins.scss
src/components/panel/__snapshots__/panel.test.tsx.snap
src/components/panel/panel.tsx
src/components/side_nav/_index.scss
src/components/split_button/_split_button_control.scss
src/global_styling/variables/_buttons.scss
src/global_styling/variables/_index.scss
src/global_styling/variables/_panel.scss
src/global_styling/variables/_side_nav.scss
src/themes/oui-next/global_styling/variables/_buttons.scss
src/themes/oui-next/global_styling/variables/_index.scss
src/themes/oui-next/global_styling/variables/_panel.scss
src/themes/oui-next/global_styling/variables/_side_nav.scss
src/themes/v9/global_styling/variables/_buttons.scss
src/themes/v9/global_styling/variables/_colors.scss
src/themes/v9/global_styling/variables/_form.scss
src/themes/v9/global_styling/variables/_index.scss
src/themes/v9/global_styling/variables/_panel.scss
src/themes/v9/global_styling/variables/_side_nav.scss
src/themes/v9/global_styling/variables/_typography.scss

Updates to v9 theme - dark theme colors still to be updated.
New:
- Additional borderRadius sizes on Panels (might be used in osd)
- Configuration of borderRadius on Cards (might be used in osd)
- Make Side Nav variables themeable
- Make Links use font-weight `$ouiFontWeightSemiBold` (no change for existing themes)
- Make input group radius match input radius using variable
V9 updates:
- Make buttons (except icon button) have a background color (old themes use transparent)
- UX was okay with some instances of icon buttons next to regular buttons with mixed backgrounds
- Switch back to buttons having 4px radius
- Using 0 border radius for inputs
- Update light theme colors
- Make Links use a lower font-weight
- Adjust typography size + weight
Screenshots (v7 should have no changes below)
| …

Additional updates to v9 theme

---

CHANGELOG.md
src-docs/src/views/guidelines/colors/_color_section.scss
src/components/header/header_links/header_links.test.tsx
src/components/page/page_header/_page_header_content.scss
src/components/page/page_side_bar/_page_side_bar.scss
src/components/page/page_template.tsx
src/components/search_bar/_search_bar.scss
src/components/table/_responsive.scss
src/components/table/_table.scss
src/global_styling/mixins/_header.scss
src/themes/oui-next/global_styling/mixins/_header.scss
src/themes/v9/global_styling/mixins/_header.scss

Backport 5484bcc1fd9e6ee5e9b2160196f1ea6808095b3e (#1416) to 1.x
Manual backport as src/components/page/page_header/_page_header_content.scss is different in 1.x vs main
N/A

[Manual Backport 1.x] fix: Update components to respect new breakpoints (#1416)

---

CHANGELOG.md
src/global_styling/mixins/_shadow.scss
src/themes/oui-next/global_styling/mixins/_shadow.scss
src/themes/v9/global_styling/mixins/_shadow.scss

Temporary fix for Chrome's problem with rendering mask images.
OUI provides the mask-image  which Chrome 129 fails to render correctly.
It is not known if or when Chrome will fix this. Since almost all of these classes
are applied to elements with scrollbars where their content contained, containing the
paint is a safe solution.

Temporary fix for Chrome's problem with rendering mask images

---

CHANGELOG.md
package.json

Bumps changelog and version ahead of 1.14 release
N/A

Bump changelog and package.json for 1.14 release

---

src-docs/src/theme_v9_dark.scss
src-docs/src/theme_v9_light.scss
src/themes/v9/global_styling/variables/_buttons.scss
src/themes/v9/global_styling/variables/_colors.scss
src/themes/v9/global_styling/variables/_side_nav.scss
src/themes/v9/global_styling/variables/_typography.scss
src/themes/v9/v9_colors_dark.scss
wiki/consuming.md

v9 Theme updates:
- new dark colors
- some updated light colors
- correcting light/dark mode colors for component variables (was using function wrong)
- dropping fira code in favor of source code pro
Skipping changelog as this is a minor update + to make it easier to make this part of 1.14.
N/A

Update v9 colors and typography

---

CHANGELOG.md
src/components/button/_button.scss
src/components/button/button_group/_button_group.scss
src/components/split_button/_split_button_control.scss
src/global_styling/variables/_buttons.scss
src/global_styling/variables/_side_nav.scss
src/themes/oui-next/global_styling/variables/_buttons.scss
src/themes/oui-next/global_styling/variables/_side_nav.scss
src/themes/v9/global_styling/variables/_buttons.scss
src/themes/v9/global_styling/variables/_colors.scss
src/themes/v9/global_styling/variables/_header.scss
src/themes/v9/global_styling/variables/_panel.scss
src/themes/v9/global_styling/variables/_side_nav.scss
src/themes/v9/global_styling/variables/_tool_tip.scss
src/themes/v9/v9_colors_dark.scss

This reverts the button background colors change in 1.14 (removing new variable but given issues + short time frame thing its okay) and updates colors for v9 theme.
N/A

Update v9 theme colors and revert button background colors

---

CHANGELOG.md
src/themes/v9/global_styling/variables/_side_nav.scss
src/themes/v9/global_styling/variables/_tool_tip.scss

Just minor updates to v9 theme to update sidenav bg color in light mode and fix tooltip bg in dark mode (to previous value until its defined)
N/A

Update sidenav and tooltip colors in v9 theme

---

CHANGELOG.md
src-docs/src/components/guide_page/guide_page_header.tsx

update figma link to latest v2

update figma link to latest v2

---

CHANGELOG.md
src/themes/v9/global_styling/variables/_buttons.scss
src/themes/v9/global_styling/variables/_colors.scss
src/themes/v9/global_styling/variables/_form.scss
src/themes/v9/global_styling/variables/_panel.scss
src/themes/v9/global_styling/variables/_shadows.scss
src/themes/v9/global_styling/variables/_tool_tip.scss

This is an update to v9 theme colors for light mode (some have impact on dark mode) made by design.
Some changes:
Colors: 
Disabled button colors:
Text Colors:
Form border/background colors:
Panel subdued background: 
Tooltip background:
N/A

Update colors for v9 theme light

---

CHANGELOG.md
package.json
yarn.lock

This is to resolve a CVE associated with `cross-spawn-5.1.0`. The package is getting pulled in from `pre-commit`, which hasn't had any updates since roughly 2016. The change ensures that we use `cross-spawn-7.0.6` across the board.
I've verified there are no relevant breaking changes from v5-v7 with their [changelog](https://github.com/moxystudio/node-cross-spawn/blob/master/CHANGELOG.md). The only breaking changes are to remove support for Node.js under v8.
We can use this as an opportunity to shift to an actively maintained git hook tool like [husky](https://github.com/typicode/husky). This would ensure we're using a library that gets updated regularly at the cost of a small migration effort. I went with the current approach as it seems like the pattern y'all are used to and wanted to …

chore: update cross-spawn to 7.0.6

---

CHANGELOG.md
src-docs/src/components/guide_components.scss
src-docs/src/views/home/home_view.js

Refactors card layouts in OUI Documentation homepage with CSS grid for smoother responsive behavior across breakpoints
After:
https://github.com/user-attachments/assets/4fe24dbb-591a-4c5b-bb62-373008f01c86
fixes #1471

Homepage layout fix

---

CHANGELOG.md
package.json
scripts/compile-charts.js
src-docs/webpack.config.js
src/webpack.config.js
yarn.lock

This addresses 11 CVEs associated with webpack-dev-server v3.
| Resolved CVE | Vulnerable Library |
|-----|--------------------|
| CVE-2024-37890 | ws-6.2.2 |
| CVE-2024-43796 | express-4.19.2 |
| CVE-2024-45590 | body-parser-1.20.2 |
| CVE-2024-21536 | http-proxy-middleware-0.19.1 |
| CVE-2024-47764 | cookie-0.6.0 |
| CVE-2024-29415 | ip-1.1.9 |
| CVE-2024-29180 | webpack-dev-middleware-3.7.2 |
| CVE-2024-52798 | path-to-regexp-0.1.7 |
| CVE-2024-45296 | path-to-regexp-0.1.7 |
| CVE-2024-43800 | serve-static-1.15.0 |
| CVE-2024-43799 | send-0.18.0 |
fixes #389 
I was able to diff the `dist` artifacts with and without these changes. The only change across all of the generated artifacts is in the charts_theme module.
```
/******/ 	// Load entry module and return exports
- /******/ 	return …
```

(security): update webpack-dev-server to address cves

---

CHANGELOG.md
package.json

Update changelog and package.json for 1.19 release
Note: vertical button group wasn't backported into 1.x, so moving to new release, will fix main CHANGELOG separately
N/A

Update changelog and package.json for 1.19 release

---

CHANGELOG.md

Vertical button groups wasn't backported to 1.x so wasn't actually in 1.18, and there was an incorrect duplicated 1.18 header. This corrects both and updates for 1.19.
N/A

Fix changelog from 1.18 release

---

.github/workflows/build_and_test.yml
CHANGELOG.md

Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact).
This PR updates `actions/upload-artifact` from v3 to v4.

update upload-artifact and download-artifact to v4

---

.github/CODEOWNERS
CHANGELOG.md
MAINTAINERS.md

Update maintainer alias from @d-rowe to @d-buckner
N/A

Update maintainer alias from @d-rowe to @d-buckner

---

CHANGELOG.md
src/components/button/button_empty/_button_empty.scss

Removed `line-height: inherit` introduced by #1342 and use `display: flex` to fix the original issue. I believe the button `line-height` should not `inherit` as it will inherit the line-height of its parent which may result in unexpected behavior, see issue and comments in #1486 
With this commit, it also fixed the issue described in #1486

fix EmptyButton text line-height

---

CHANGELOG.md
package.json
yarn.lock

- Add package resolution to braces to be ^3.0.3. [CVE-2024-4068](https://github.com/advisories/GHSA-grv7-fg5c-xmjg).
Fixes #1509

add a package resolution for braces to ^3.0.3.

---

CHANGELOG.md
yarn.lock

Fix elliptic and axios CVE
https://advisories.opensearch.org/advisory/GHSA-vjh7-7g9h-fjfh
https://advisories.opensearch.org/advisory/CVE-2025-27152

Fix elliptic and axios CVE

---

CHANGELOG.md
package.json
src-docs/dev.webpack.config.js
src-docs/webpack.config.js
src/components/search_bar/search_bar.tsx
yarn.lock

https://github.com/opensearch-project/oui/pull/1473 upgraded versions of webpack-cli and webpack-dev-server. After these changes, runtime errors from ResizeObservable bubbled up to the dev server overlay causing a loop and error for certain components. This doesn't impact the production build, and this code is already out in 1.19. 
The MV upgrade of webpack-cli removed a WEBPACK_DEV_SERVER env variable, which enables us to not show runtime errors in the overlay (fixing the issue above), but also pointed out that the dev server config wasn't updated (which I did here). 
I had to drop deasync because it caused an infinite loop (unclear why this changed behavior). Other sync libraries to get ports had other issues (cves, unnecessary dependencies) and using async/await in the same file failed …

Fix dev server configuration after webpack-dev-server upgrade in 1.19

---

CHANGELOG.md
src/components/code/_code_block.tsx
src/components/tool_tip/tool_tip.tsx
yarn.lock

Takes https://github.com/opensearch-project/oui/pull/1565 + addresses build failures to resolve cve
Note: disabling lint errors because they are existing functionality and not trying to change that atm.
Fixes #1518

Update eslint plugin jsx a11y 6.x

---

CHANGELOG.md
package.json
src/components/basic_table/basic_table.tsx
src/components/page/page_template.tsx
src/components/search_bar/query/date_format.ts
src/utils/prop_types/is.ts
yarn.lock

Updates TypeScript to 4.7.4
I think this will unblock refractor version update (https://github.com/opensearch-project/oui/pull/1574) due to package.json exports support. Worst case otherwise is just more strict typing.
N/A

Update TypeScript to 4.7.4

---

CHANGELOG.md
package.json
yarn.lock

Update babel-plugin-add-module-exports to 1.0.4
Fixes #1351

Update babel-plugin-add-module-exports to 1.0.4
